:construction: Worked on German translation of Tic-Tac-Toe Tutorial
reactjs/de.reactjs.org pull request #174
Opened 2020-11-09 14:32 UTC by liza-kl

#34 

I worked a little bit on the Translation, might continue in the next couple of days and then proof-read it :) 
Cheers

2021-01-07 18:36 UTC, miku86 commented
Hey folks,

I will review it on Saturday.

@liza-kl, thanks for your awesome efforts,
we really appreciate it!

2021-01-09 08:07 UTC, miku86 commented on content/tutorial/tutorial.md
> +Veränderungen  in variablen Objekten zu erkennen ist schwierig, da sie direkt verändert werden.
```suggestion
Veränderungen in variablen Objekten zu erkennen ist schwierig, da sie direkt verändert werden.
```

2021-01-09 08:07 UTC, miku86 commented on content/tutorial/tutorial.md
> + Zur Erkennung müsste das variable Objekt mit seinen alten Kopien vergleichen werden --
```suggestion
 Zur Erkennung müsste das variable Objekt mit seinen alten Kopien verglichen werden --
```

2021-01-09 08:13 UTC, miku86 commented on content/tutorial/tutorial.md
> +Falls das unveränderliche Objekt auf ein anderes verwiesen wird, als das vorhergehende, so hat das Objekt sich verändert.
```suggestion
Falls das unveränderliche Objekt, auf das verwiesen wird, ein anderes ist als das vorhergehende, dann hat sich das Objekt verändert.
```

2021-01-09 08:17 UTC, miku86 commented on content/tutorial/tutorial.md
> +#### Entscheiden wann Re-Rendern in React {#determining-when-to-re-render-in-react}
```suggestion
#### Entscheiden, wann neu gerendert werden soll {#determining-when-to-re-render-in-react}
```

Ich habe das ein wenig freier korrigiert. 

`wann gererendert werden soll` klingt ziemlich sperrig.

Damit es kurz bleibt, habe ich `in React` gelöscht, da es mir redundant erscheint.

2021-01-09 08:33 UTC, miku86 commented on content/tutorial/tutorial.md
> + welche helfen zu entscheiden, ob eine Komponente re-rendered werden muss.
```suggestion
Durch unveränderbare Daten kann leicht ermittelt werden, ob Veränderungen gemacht worden sind, was hilft zu entscheiden, ob eine Komponente neu gerendert werden muss. 
```

Habe das `durch``hinzugefügt, damit klar ist, dass die Daten selbst nichts machen, sondern Immutability als Werkzeug genutzt wird.

2021-01-09 08:34 UTC, miku86 commented on content/tutorial/tutorial.md
> + Unveränderbarer Daten können leicht entscheiden, ob Veränderungen gemacht worden sind
```suggestion
Durch unveränderbare Daten kann leicht ermittelt werden, ob Veränderungen gemacht worden sind, 
```

Habe das `durch``hinzugefügt, damit klar ist, dass die Daten selbst nichts machen, sondern Immutability als Werkzeug genutzt wird.

2021-01-09 08:35 UTC, miku86 commented on content/tutorial/tutorial.md
> +Du kannst mehr über `shouldComponentUpdate()` lernen und wie Du *pure components* entnwickelst, wenn Du das hier liest [Optimizing Performance](/docs/optimizing-performance.html#examples).
```suggestion
Du kannst mehr über `shouldComponentUpdate()` lernen und wie Du *pure components* entwickelst, wenn Du das hier liest [Optimizing Performance](/docs/optimizing-performance.html#examples).
```

2021-01-09 08:35 UTC, miku86 commented on content/tutorial/tutorial.md
>  ### Funktionskomponente {#function-components}
```suggestion
### Funktionskomponenten {#function-components}
```

2021-01-09 08:39 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir verändern nun die Square Komoponente zu einer  **function component/ Funktionskomponente**.
```suggestion
Wir verändern nun die Square-Komponente zu einer **Funktionskomponente**.
```

Habe die anderen Übersetzungen angeschaut und deshalb den englischen Begriff entfernt.

2021-01-09 08:40 UTC, miku86 commented on content/tutorial/tutorial.md
> +In React, **function components/Funktionskomponenten** sind ein leichterer Weg um Komponenten zu schreiben,
```suggestion
In React sind **Funktionskomponenten** ein leichterer Weg, um Komponenten zu schreiben,
```

2021-01-09 08:41 UTC, miku86 commented on content/tutorial/tutorial.md
> + welche nur eine `render` Methode beinhalten und keinen eigenen Zustand / state haben.
```suggestion
 welche nur eine `render`-Methode beinhalten und keinen eigenen Zustand haben.
```

2021-01-09 08:43 UTC, miku86 commented on content/tutorial/tutorial.md
> +Ersetze die Square Klasse mit diesem Code:
```suggestion
Ersetze die Square-Klasse mit diesem Code: 

```

Sehr wahrscheinlich muss hier eine Leerzeile eingefügt werden, damit der folgende Code-Block korrekt gerendert wird.

2021-01-09 08:45 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir haben `this.props` mit `props` ersetzt, beide Male wird es angezeigt.
```suggestion
Wir haben alle vorkommenden `this.props` mit `props` ersetzt.
```

2021-01-09 08:58 UTC, miku86 commented on content/tutorial/tutorial.md
> +> in einer Funktionskomponente brauchen wir uns keine Gedanken über `this` zu machen..
```suggestion
> Als wir die Square-Klasse zu einer Funktionskomponente verändert haben, haben wir auch `onClick={() => this.props.onClick()}` zu einem kürzeren `onClick={props.onClick}` geändert (bemerke, dass die Klammern auf *beiden* Seiten fehlen). In der Klasse haben wir eine Pfeilfunktion benutzt, um den korrekten `this` Wert zu erhalten, in einer Funktionskomponente müssen wir uns keine Gedanken über `this` machen..
```

Die spanische und französische Übersetzungen nutzen eine 1-zu-1-Übersetzung. Ich denke, dass das hier Sinn macht, vor allem verbunden mit dem `=>`.

2021-01-09 09:05 UTC, miku86 commented on content/tutorial/tutorial.md
> +Nun müssen wir einen offensichtlichen Fehler in unserer Tic-Tac-Toe Anwendung beheben: Die "O"s können nicht auf dem Spielbord markiert werden.
```suggestion
Nun müssen wir einen offensichtlichen Fehler in unserer Tic-Tac-Toe Anwendung beheben: Die "O"s können nicht auf dem Spielfeld markiert werden.
```

`Bord` hört sich für mich sehr "physisch" an, wie ein Brett an der Wand. Habe hier einfach `Spielfeld` vom Wikipedia-Artikel von Tic-Tac-Toe genommen.

2021-01-09 09:12 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir können dies standardmäßig setzen, wenn wir den Initial State in unserem Board Constructor verändern:
```suggestion
Wir können diesen Zug standardmäßig setzen, indem wir den Grundzustand in unserem Board-Konstruktor verändern:
```

2021-01-09 09:16 UTC, miku86 commented on content/tutorial/tutorial.md
> +Jedes Mal wenn ein Spieler einen Zug unternimmt, `xIsNext` (ein Boolean) wird geändert um den nächsten Spieler zu bestimmen und der Zustand / State des Spiels wird gespeichert.
```suggestion
Jedes Mal wenn ein Spieler einen Zug unternimmt, wird `xIsNext` (ein Boolean) geändert, um den nächsten Spieler zu bestimmen und der Zustand des Spiels wird gespeichert.
```

Wir könnten `umgedreht` anstatt `geändert` nutzen, damit klar ist, dass ein Boolean nur wie eine Münze zwei mögliche Zustände hat. Meinungen?

2021-01-09 09:17 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir aktualisieren die `handleClick` Funktion des Boards um den Wert von `xIsNext` zu flippen:
```suggestion
Wir aktualisieren die `handleClick`-Funktion des Boards, um den Wert von `xIsNext` umzudrehen:
```

2021-01-09 09:20 UTC, miku86 commented on content/tutorial/tutorial.md
> +Mit dieser Änderung können "X"s und "O"s Spielzüge annehmen.
```suggestion
Durch diese Änderung wechseln sich "X"s und "O"s ab.
```

2021-01-09 09:21 UTC, miku86 commented on content/tutorial/tutorial.md
> +Lasst uns ebenfalls den "status" text in der Boards `render` Funktion ändern, so dass es anzeigt, welcher Spieler als nächstes an der Reihe ist:
```suggestion
Lasst uns ebenfalls den "status"-Text in Board's `render`-Funktion ändern, so dass sie anzeigt, welcher Spieler als nächstes an der Reihe ist:
```

2021-01-09 09:22 UTC, miku86 commented on content/tutorial/tutorial.md
> +Nach dem wir diese Veränderungen angewandt haben, sollte die Board Komponent nun so aussehen:
```suggestion
Nachdem wir diese Veränderungen angewandt haben, sollte die Board-Komponent nun so aussehen:
```

2021-01-09 09:25 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir können einen Gewinner bestimmen, in dem wir diese Helper-Funktion an das Ende der Datei schreiben:
```suggestion
Da wir nun den nächsten Spieler anzeigen können, sollten wir ebenfalls anzeigen, wann das Spiel gewonnen ist und dass keine Züge mehr möglich sind. Wir können einen Gewinner bestimmen, indem wir diese Helfer-Funktion an das Ende der Datei schreiben:
```

2021-01-09 09:26 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir werden `calculateWinner(squares)` in der Boards `render` Funktion aufrufen, um zu prüfen, ob ein Spieler gewonnen hat.
```suggestion
Wir werden `calculateWinner(squares)` in Board's `render`-Funktion aufrufen, um zu prüfen, ob ein Spieler gewonnen hat.
```

2021-01-09 09:27 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir ersetzen die `status` Deklaration in der Boards `render` Funktion mit folgendem Code:
```suggestion
Wir ersetzen die `status`-Deklaration in Boards `render`-Funktion mit folgendem Code:
```

2021-01-09 09:29 UTC, miku86 commented on content/tutorial/tutorial.md
>  **[View the full code at this point](https://codepen.io/gaearon/pen/LyyXgK?editors=0010)**
```suggestion
**[Den ganzen Quellcode an diesem Punkt anschauen](https://codepen.io/gaearon/pen/LyyXgK?editors=0010)**
```

2021-01-09 09:32 UTC, miku86 commented on content/tutorial/tutorial.md
> +Als abschließende Übung, lass uns eine "History" hinzufügen, um zu älteren Zügen im Spiel zurückzukommen.
```suggestion
Lass uns als abschließende Übung eine "Versionsgeschichte" hinzufügen, um zu älteren Zügen im Spiel zurückzukommen.
```

Ich habe `Versionsgeschichte` von Wikipedia übernommen.

2021-01-09 09:35 UTC, miku86 commented on content/tutorial/tutorial.md
> +Falls wir das `squares` Array verändern würden, wäre eine Implementierung von Verlaufsspeicherung sehr schwierig..
```suggestion
Hätten wir das `squares`-Array veränderbar gemacht, wäre die Implementierung einer Versionsgeschichte sehr schwierig..
```

Wäre hier ein Link zur Sektion `Veränderung erkennen` sinnvoll?

2021-01-09 09:40 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wie auch immer, wir verwendeten `slice()` um eine neue Kopie des `squares` Arrays nach jedem Zug zu erstellen, und [behandelten es wie ein Unveränderliches](#why-immutability-is-important).
```suggestion
Wir verwendeten jedoch `slice()`, um eine neue Kopie des `squares`-Arrays nach jedem Zug zu erstellen und [behandelten den Array als unveränderbar](#why-immutability-is-important). 
```

`als unveränderbar behandeln` klingt extrem seltsam. Ideen?

2021-01-09 09:41 UTC, miku86 commented on content/tutorial/tutorial.md
> +Dies wird uns erlauben, jede ältere Version des `squares` Array zu speichern, und zwischen den Zügen zu springen, welche schon stattfanden.
```suggestion
Dies erlaubt uns, jede ältere Version des `squares`-Array zu speichern, und zwischen den Zügen zu springen, welche schon stattfanden.
```

2021-01-09 09:43 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir werden die alten `squares` Arrays in einem andeeren Array `history` speichern. Das `history` Array repräsentiert alle Board Zustände / States, vom ersten bis zum letzten Zug und hat folgende Form
```suggestion
Wir werden die alten `squares`-Arrays in einem anderen Array mit dem Namen `history` speichern. Das `history`-Array repräsentiert alle Zustände des Spielfelds, vom ersten bis zum letzten Zug und hat folgende Form:
```

2021-01-09 09:44 UTC, miku86 commented on content/tutorial/tutorial.md
> +Nun müssen wir entscheiden, welche Komponente den `history` Zustand/State beinhalten wird.
```suggestion
Nun müssen wir entscheiden, welche Komponente den `history`-Zustand beinhalten wird.
```

2021-01-09 09:48 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir möchten dass die Top-Level-Game-Komponente eine Liste der bisherigen Züge anzeigt.
```suggestion
Wir möchten, dass die oberste `Game`-Komponente eine Liste der bisherigen Züge anzeigt.
```

2021-01-09 09:49 UTC, miku86 commented on content/tutorial/tutorial.md
> +Diese Liste braucht Zugriff auf `history` brauchen um dies zu tun.
```suggestion
Um dies zu tun, benötigt diese Liste Zugriff auf `history`.
```

2021-01-09 09:50 UTC, miku86 commented on content/tutorial/tutorial.md
> +Demnach platzieren wir den `history` State in der Top-Level-Game-Komponente.
```suggestion
Deshalb platzieren wir den `history`-Zustand in der obersten Komponente, `Game`.
```

2021-01-09 10:00 UTC, miku86 commented on content/tutorial/tutorial.md
> +Die gibt der Game Komponente völlige Kontrolle über die Daten vom Board, und es weist das Board an, zu rendern zu den älteren Zügen aus der `history`.
```suggestion
Das Platzieren des `history`-Zustandes in der `Game`-Komponente erlaubt uns das Entfernen des `squares`-Zustandes von dessen Unterkomponente `Board`. So wie wir den Zustand von der `Square`-Komponente in die `Board`-Komponente ["angehoben haben"](#lifting-state-up), so heben wir diesen nun von der `Board` in die `Game`-Komponente. Das gibt der `Game`-Komponente völlige Kontrolle über die Daten des Boards und lässt sie das Board anweisen, frühere Züge aus der `history` zu rendern.
```

2021-01-09 10:01 UTC, miku86 commented on content/tutorial/tutorial.md
> +Als erstes setzen wir den Initial State für die Game Komponente in deren Constructor:
```suggestion
Als erstes setzen wir den Grundzustand für die Game-Komponente in deren KonstruKtor:
```

2021-01-09 10:03 UTC, miku86 commented on content/tutorial/tutorial.md
> +Als nächstes haben wir die Board Komponente, welche die `squares` und `onClick` props erhält von der Game Komponente.
```suggestion
Als nächstes haben wir die Board-Komponente, welche die `squares` und `onClick`-props von der Game-Komponente erhält .
```

2021-01-09 10:06 UTC, miku86 commented on content/tutorial/tutorial.md
> +Hier sind die benötigten Schritte, um die Board Komponente zu verändern:
```suggestion
Da wir nun einen einzigen Klick-Handler im Board für viele Squares haben, müssen wir die Position von jedem Square in den `onClick`-Handler übergeben, um anzugeben, welches Square geklickt worden ist. Hier sind die benötigten Schritte, um die Board-Komponente zu verändern:
```

2021-01-09 10:06 UTC, miku86 commented on content/tutorial/tutorial.md
> +* Ersetze `this.state.squares[i]` mit `this.props.squares[i]` in der Board `renderSquare` Funktion.
```suggestion
* Ersetze `this.state.squares[i]` mit `this.props.squares[i]` in der Board `renderSquare`-Funktion.
```

2021-01-09 10:06 UTC, miku86 commented on content/tutorial/tutorial.md
> +* Ersetze `this.handleClick(i)` mit `this.props.onClick(i)` in der Board `renderSquare` Funktion.
```suggestion
* Ersetze `this.handleClick(i)` mit `this.props.onClick(i)` in der Board `renderSquare`-Funktion.
```

2021-01-09 10:07 UTC, miku86 commented on content/tutorial/tutorial.md
> +Die Board Komponente sieht nun so aus:
```suggestion
Die Board-Komponente sieht nun so aus:
```

2021-01-09 10:09 UTC, miku86 commented on content/tutorial/tutorial.md
> +um den aktuellsten histroy-Eintrag zu verwenden, um den aktuellen Game-Status zu bestimmen.
```suggestion
Wir aktualisieren die `render`-Funktion in der Game-Komponente, um den letzten Eintrag der Versionsgeschichte zu verwenden und den aktuellen Spielzustand anzuzeigen. 
```

2021-01-09 10:11 UTC, miku86 commented on content/tutorial/tutorial.md
> +Nach dem Refactoring sollte die `render` Funktion im Board so aussehen:
```suggestion
Da die Game-Komponente nun den Spielzustand rendert, können wir den dazugehörigen Code aus Boards `render`-Funktion entfernen. Nach dem Veränderung sollte die `render`-Funktion im Board so aussehen:
```

Ich habe `Methode` und `Refactoring` geändert, damit der Leser nicht verwirrt wird durch neue Begriffe.

2021-01-09 10:13 UTC, miku86 commented on content/tutorial/tutorial.md
> +Als letztes müssen wir nun die `handleClick` Methode aus der Board Komponente in die Game Komponente verlagern.
```suggestion
Als letztes müssen wir nun die `handleClick`-Methode aus der Board-Komponente in die Game-Komponente verlagern.
```

2021-01-09 10:14 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir müssen auch die `handleClick` verändern,da die State aus der Game Komponente eine andere Struktur hat.
```suggestion
Wir müssen `handleClick` auch verändern, da der Zustand aus der Game-Komponente eine andere Struktur hat.
```

2021-01-09 10:17 UTC, miku86 commented on content/tutorial/tutorial.md
> +Mit der Game `handleClick` Methode konkatenieren wir die neuen history-Einträge in `history`.
```suggestion
In der `handleClick`-Methode von Game fügen wir die neuen Einträge der Versionsgeschichte der bestehenden `history` hinzu.
```

Ich habe das ein wenig vereinfacht, da ich davon ausgehe, dass die wenigsten Leser wissen, was `konkatenieren` bedeutet.

2021-01-09 10:19 UTC, miku86 commented on content/tutorial/tutorial.md
> +>Anders als bei der Array `push()` Methode, welche Du vielleicht eher kennst, verändert die `concat()` method doesn't das ursprüngliche Array,weshalb wir dieses bevorzugen.
```suggestion
>Anders als die Array `push()`-Methode, welche Du vielleicht eher kennst, verändert die `concat()`-Methode den ursprünglichen Array nicht, weshalb wir diese bevorzugen.
```

2021-01-09 10:20 UTC, miku86 commented on content/tutorial/tutorial.md
> +An diesem Punkte benötigt die Bord Komponente nur die `renderSquare` und die `render` Methode.
```suggestion
An diesem Punkte benötigt die Board-Komponente nur noch die `renderSquare` und `render` -Methoden. 
```

2021-01-09 10:21 UTC, miku86 commented on content/tutorial/tutorial.md
> +Das Spiel-State und die `handleClick` Methode sollten sich in der Game Komponente befinden.
```suggestion
Der Spielzustand und die `handleClick`-Methode sollten sich in der Game-Komponente befinden. 
```

2021-01-09 10:22 UTC, miku86 commented on content/tutorial/tutorial.md
> +Seit wir den Verlauf des Tic-Tac-Toes Spiel speichern, können wir diese dem Spieler als eine Liste der letzten Züge anzeigen.
```suggestion
Seit wir den Verlauf des Tic-Tac-Toes Spiel speichern, können wir diesen dem Spieler als eine Liste der letzten Züge anzeigen.
```

2021-01-09 10:25 UTC, miku86 commented on content/tutorial/tutorial.md
> +Wir können diese in unserer Anwendung durchgeben. Um mehrere Sachen in React rendern zu können, können wir das Array aus den React Elementen verwenden.
```suggestion
Wir haben vorhin gelernt, dass React-Elemente erstklassige JavaScript-Objekte sind; wir können diese in unserer Anwendung herumbewegen. Um mehrere Elemente in React rendern zu können, können wir einen Array an React-Elementen verwenden.
```

2021-01-09 10:28 UTC, miku86 commented on content/tutorial/tutorial.md
> +Arrays haben in Java-Script eine [`map()` Methode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) welche verwendet wird um Daten auf andere Daten zu mappe
```suggestion
Arrays haben in JavaScript eine [`map()`-Methode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), welche verwendet wird um Daten auf andere Daten zu mappen, wie zum Beispiel:
```

2021-01-09 10:31 UTC, miku86 commented on content/tutorial/tutorial.md
> +Das Verwenden der `map` Methode, we can map our history of moves to React elements representing buttons on the screen, and display a list of buttons to "jump" to past moves.
```suggestion
Durch das Verwenden der `map`-Methode können wir den Verlauf unserer Züge auf React-Elemente abbilden, die Buttons auf dem Bildschirm darstellen und eine Liste von Buttons anzeigen, um zu vergangenen Zügen zu "springen".
```

2021-01-09 10:32 UTC, miku86 commented on content/tutorial/tutorial.md
>  Let's `map` over the `history` in the Game's `render` method:
```suggestion
Lass und über die `history` in Games `render`-Methode mappen.
```

2021-01-09 10:34 UTC, miku86 commented on content/tutorial/tutorial.md
> +* Den Spielverlauf zu betrachten und alte Ansichten des Spiel-Boards zu sehen.
```suggestion
* Den Spielverlauf zu betrachten und alte Ansichten des Spielbretts aufzurufen.
```

2021-01-09 10:35 UTC, miku86 commented on content/tutorial/tutorial.md
> +2. Markiere das ausgewählte Element in der Zug Liste fett.
```suggestion
2. Markiere das ausgewählte Element in der Zugliste fett.
```

2021-01-09 10:36 UTC, miku86 commented on content/tutorial/tutorial.md
> +3. Schreibe das Board so, dass Du zwei Schleifen verwendest um die Quadrate in dem Bord zu erzeugen, anstatt sie zu hardcoden.
```suggestion
3. Schreibe Board so, dass Du zwei Schleifen verwendest um die Quadrate im Spielbrett zu erzeugen, anstatt sie zu hardcoden.
```

2021-01-09 10:37 UTC, miku86 commented on content/tutorial/tutorial.md
> +4. Füge einen Toggle Button hinzu, welcher dir erlaubt die Züge in aufsteigender oder absteigender Ordnung zu sortieren.
```suggestion
4. Füge einen Umschalt-Button hinzu, welcher dir erlaubt die Züge in aufsteigender oder absteigender Ordnung zu sortieren.
```

2021-01-09 10:38 UTC, miku86 commented on content/tutorial/tutorial.md
> +aber gib es doch eine Chance.** Die Techniken die du in diesem Tutorial lernen wirst, sind fundamental um eine React-App zu erstellen, es zu meistern wird dir ein tiefes Verständnis von React geben.
```suggestion
aber gib es doch eine Chance.** Die Techniken, die du in diesem Tutorial lernen wirst, sind fundamental um eine React-App zu erstellen, es zu meistern wird dir ein tiefes Verständnis von React geben.
```

2021-01-09 10:55 UTC, miku86 requested changes
Hey Lisa,

vielen Dank für deine tolle Arbeit! :)

Ich habe ein paar Bemerkungen/Empfehlungen gemacht.

Bitte schau dir jede Bemerkung/Empfehlung an und stimme ihr zu (`Commit suggestion`) oder schreib einen Kommentar, damit wir uns darüber austauschen können. Du kannst auch einen [großen Batch an Commits machen](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request)

Ich denke, das war der letzte große Brocken der Dokumentation.

Grüße
Michael

2021-02-08 08:56 UTC, miku86 commented
Hey @liza-kl,

hope you're doing well!

It would be cool to keep the ball rolling.
Please let us know if you are interested in having a look at this.
No hard feelings if you're not, just to know the current situation :slightly_smiling_face:.

Greetings
Michael

2021-03-05 07:11 UTC, pop1989bb commented
Guten Morgen,
ich würde bei der Vervollständigung etc. auch unterstützen wollen, bin aber (als seltener GitHub-Nutzer) etwas verwirrt, weil bei mir immer die Meldung kommt, dass ich mich nicht in einem Branch befinde. Falls ich helfen kann, lasst es mich gerne wissen.

2021-04-01 11:09 UTC, miku86 approved these changes

2021-04-01 11:17 UTC, miku86 commented
Hey folks,

I just approved my own suggestions, so that we can finish this task.

@ph1p Can we ignore the missing Vercel deployment check?

@pop1989bb Sorry for missing your reply. You can simply create your own pull requests after this current pull request will be merged. Reach out if you need some help.

Greetings
Michael

2021-04-01 11:47 UTC, ph1p commented
Hmm the error on vercel is new to me, but I think we can merge the changes for now. 
Looks good to me! 👍

2021-04-01 11:48 UTC, ph1p approved these changes

2021-04-01 11:48 UTC, merged