Docs/hooks api reference
reactjs/de.reactjs.org pull request #272
Opened 2022-07-04 19:47 UTC by PReichetanz

## Translation for `Hooks API Reference`

All comments and ideas for further improving the translation are very much appreciated!

2023-01-03 14:17 UTC, ph1p requested changes

2023-01-03 14:17 UTC, ph1p commented on content/docs/hooks-reference.md
> +Eine Komponente, die `useContext` aufruft, wird immer neu gerendert, wenn sich der Kontextwert ändert. Wenn ein erneutes Rendering aufwendig is, kann man es [mithilfe von Memoisierung optimieren](htt
```suggestion
Eine Komponente, die `useContext` aufruft, wird immer neu gerendert, wenn sich der Kontextwert ändert. Wenn ein erneutes Rendering aufwendig ist, kann man es [mit Hilfe von Memoisierung optimieren](https://github.com/facebook/react/issues/15156#issuecomment-474590693).
```

2023-01-03 14:17 UTC, ph1p commented on content/docs/hooks-reference.md
> +>React garantiert, dass die Identität der Funktion `dispatch` stabil ist und sich bei erneuten Renderings nicht ändert.  Deshalb kann die Funktion problemlos aus der Liste der Abhängigkeiten des useE
```suggestion
>React garantiert, dass die Identität der Funktion `dispatch` stabil ist und sich bei erneuten Renderings nicht ändert. Deshalb kann die Funktion problemlos aus der Liste der Abhängigkeiten von useEffect oder useCallback gelassen werden.
```

2023-01-05 07:44 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +#### Fauler initialer State {#lazy-initial-state}
Good point, agreed!

2023-01-05 07:54 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Allerdings können nicht alle Auswirkungen aufgeschoben werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Be
We have used the female form "die State Hook" above, so I think it should read here something like this:
```suggestion
Allerdings können nicht alle Auswirkungen aufgeschoben werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Benutzer keine visuelle Inkonsistenz wahrnimmt. (Die Unterscheidung ist konzeptionell ähnlich wie die zwischen passiven und aktiven Event Listenern).  Für diese Arten von Effekten bietet React eine zusätzliche Hook namens [`useLayoutEffect`](#uselayouteffect). Sie hat die gleiche Signatur wie `useEffect` und unterscheidet sich nur darin, wann sie ausgelöst wird.
```
However, I am not sure here: Do we want to use female word forms for "hook" in German? If so, there are some other places in this document as well where we have to adapt it because I used the male form.

2023-01-05 08:05 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +>React garantiert, dass die Identität der Funktion `dispatch` stabil ist und sich bei erneuten Renderings nicht ändert.  Deshalb kann die Funktion problemlos aus der Liste der Abhängigkeiten des useE
To be coherent, it should read (like the note in the `useState` section):
```suggestion
>React garantiert, dass die Identität der Funktion `dispatch` stabil ist und sich bei erneuten Renderings nicht ändert.  Deshalb kann die Funktion problemlos aus der Liste der Abhängigkeiten von `useEffect` oder `useCallback` ausgelassen werden.
```

2023-01-05 08:18 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Die Signatur dieses Hooks ist identisch mit `useEffect`, aber er wird synchron nach allen DOM-Mutationen ausgelöst. Verwende ihn, um das Layout aus dem DOM zu lesen und synchron neu zu rendern. Aktua
As mentioned above, I am not sure why we use the female form here: 
Does it refer to "die Signatur" or implicitly to "die `useLayoutEffect Hook`? 

If the ladder, why do we write "Die Signatur dieses Hooks" instead of "Die Signatur dieser Hook"?

2023-01-05 08:21 UTC, PReichetanz commented
Hey @ph1p,
thank you very much for your review and suggestions, I have learned a lot!

I have agreed on almost all issues you have remarked; there are, however, three issues left where I am not sure how to handle them.

Could you please have a look again so that we can discuss what do to here?

Thank you very much again!

2023-01-05 11:17 UTC, ph1p commented on content/docs/hooks-reference.md
> +Allerdings können nicht alle Auswirkungen aufgeschoben werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Be
I've updated my suggestion. I think "der Hook" is right, because of "der Haken".

2023-01-05 13:21 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Die Signatur dieses Hooks ist identisch mit `useEffect`, aber er wird synchron nach allen DOM-Mutationen ausgelöst. Verwende ihn, um das Layout aus dem DOM zu lesen und synchron neu zu rendern. Aktua
I have checked some other pages of the German docs and found the male version for hook:
- [Regeln von Hooks](https://de.reactjs.org/docs/hooks-rules.html)
- [Eigene Hooks bauen](https://de.reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook)
- [Benutzen der State Hook#Was ist ein Hook?](https://de.reactjs.org/docs/hooks-state.html#whats-a-hook)

I think the last one shows the problem itself: The page name "Benutzen der State Hook" uses female, but the subheading "Was ist ein Hook" (and all other instances on the page) are male.

My personal feeling is that "Hook" should rather be male, but I'm afraid that this is rather subjective.

2023-01-05 13:22 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Allerdings können nicht alle Auswirkungen aufgeschoben werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Be
This is my feeling as well (as commented below a minute ago). I will immediately make suggestions with the male version.

2023-01-05 13:24 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Allerdings können nicht alle Auswirkungen aufgeschoben werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Be
I've found another whitespace:
```suggestion
Allerdings können nicht alle Auswirkungen aufgeschoben (engl. deferred) werden. So muss beispielsweise eine DOM-Mutation, die für den Benutzer sichtbar ist, synchron vor dem nächsten Malvorgang erfolgen, damit der Benutzer keine visuelle Inkonsistenz wahrnimmt. (Die Unterscheidung ist konzeptionell ähnlich wie die zwischen passiven und aktiven Event Listenern). Für diese Arten von Effekten bietet React einen zusätzlichen Hook namens [`useLayoutEffect`](#uselayouteffect). Dieser hat die gleiche Signatur wie `useEffect` und unterscheidet sich nur darin, wann er ausgelöst wird.
```

2023-01-05 13:26 UTC, PReichetanz commented on content/docs/hooks-reference.md
> +Die Signatur dieses Hooks ist identisch mit `useEffect`, aber er wird synchron nach allen DOM-Mutationen ausgelöst. Verwende ihn, um das Layout aus dem DOM zu lesen und synchron neu zu rendern. Aktua
@ph1p As far as I can see, this conversation is now outdated and can be resolved, right?

2023-01-17 08:37 UTC, ph1p commented on content/docs/hooks-reference.md
> +Die Signatur dieses Hooks ist identisch mit `useEffect`, aber er wird synchron nach allen DOM-Mutationen ausgelöst. Verwende ihn, um das Layout aus dem DOM zu lesen und synchron neu zu rendern. Aktua
https://www.duden.de/rechtschreibung/Hook yes, the duden also says it's masculine

2023-01-17 08:40 UTC, ph1p commented
Sorry for the delay. All problems are solved now and we are ready to merge. Thank you! (:

2023-01-17 08:41 UTC, ph1p approved these changes

2023-01-17 08:41 UTC, merged