Translated Test-Rezepte
reactjs/de.reactjs.org pull request #294
Opened 2023-01-06 13:29 UTC by michael-schantin

2023-01-17 08:31 UTC, ph1p requested changes
Thank you! :) I have added a few suggestions

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +Verschiedene DOM-Ereignisse und ihre Eigenschaften werden in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) beschrieben. Beachten Sie, dass Sie `{ bubbles: true }` in jedem von Ih
```suggestion
Verschiedene DOM-Events und ihre Eigenschaften werden in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) beschrieben. Beachte, dass Du `{ bubbles: true }` in jedem von deinen erstellten Events übergeben musst, damit es den React-Listener erreicht, da React-Events automatisch an den Stamm (engl. root) delegiert werden.
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +Ihr Code könnte zeitgeberbasierte Funktionen wie `setTimeout` verwenden, um mehr Arbeit in der Zukunft zu planen. In diesem Beispiel wartet ein Multiple-Choice-Feld auf eine Auswahl und rückt vor, wo
```suggestion
Dein Code könnte zeitgeberbasierte Funktionen wie `setTimeout` verwenden, um mehr Arbeit in der Zukunft zu planen. In diesem Beispiel wartet ein Multiple-Choice-Feld auf eine Auswahl und rückt vor, wobei eine Zeitüberschreitung eintritt, wenn innerhalb von 5 Sekunden keine Auswahl getroffen wird:
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +Sie können gefälschte Timer nur in einigen Tests verwenden. Oben haben wir sie aktiviert, indem wir `jest.useFakeTimers()` aufgerufen haben. Der Hauptvorteil, den sie bieten, besteht darin, dass Ihr
```suggestion
Du kannst Fake-Timer nur in einigen Tests verwenden. Oben haben wir sie aktiviert, indem wir `jest.useFakeTimers()` aufgerufen haben. Der Hauptvorteil, den sie bieten, besteht darin, dass dein Test nicht wirklich fünf Sekunden auf die Ausführung warten  und du den Komponentencode auch nicht nur zum Testen komplizierter machen musst.
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +Mit Frameworks wie Jest können Sie mit [`toMatchSnapshot` / `toMatchInlineSnapshot`](https://jestjs.io/docs/en/snapshot-testing) auch "Schnappschüsse" von Daten speichern. Mit diesen können wir die g
```suggestion
Mit Frameworks wie Jest kannst Du mit [`toMatchSnapshot` / `toMatchInlineSnapshot`](https://jestjs.io/docs/en/snapshot-testing) auch "Schnappschüsse" von Daten speichern. Mit diesen können wir die gerenderte Komponentenausgabe "speichern" und sicherstellen, dass eine Änderung daran explizit als Änderung am Snapshot festgeschrieben werden muss.
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +In seltenen Fällen führen Sie möglicherweise einen Test für eine Komponente aus, die mehrere Renderer verwendet. Beispielsweise können Sie Snapshot-Tests auf einer Komponente mit `react-test-renderer
```suggestion
In seltenen Fällen führen Sie möglicherweise einen Test für eine Komponente aus, die mehrere Renderer verwendet. Beispielsweise kannst du Snapshot-Tests auf einer Komponente mit `react-test-renderer` ausführen, die intern `render` von `react-dom` innerhalb einer untergeordneten Komponente verwendet, um einige Inhalte zu rendern. In diesem Szenario können Sie Aktualisierungen mit `act()`s umschließen, die ihren Renderern entsprechen.
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +Wenn ein gängiges Szenario nicht abgedeckt ist, teilen Sie uns dies bitte auf der [Problemverfolgungswebsite](https://github.com/reactjs/reactjs.org/issues) für die Dokumentation mit.
```suggestion
Wenn ein gängiges Szenario nicht abgedeckt ist, teile uns dies bitte im [Issue-Tracker](https://github.com/reactjs/reactjs.org/issues) für die Dokumentation mit.
```

2023-01-17 08:31 UTC, ph1p commented on content/docs/testing-recipes.md
> +    render(<Hallo />, container);
```suggestion
    render(<Hello />, container);
```
We decided to translate only comments and plain text to keep it consistent. Not the code itself.

2023-01-19 12:04 UTC, michael-schantin commented
I agree to all changes, is there anything else I need to do to make the PR gemer

2023-01-19 12:21 UTC, ph1p commented
Nope :) Thank you very much!

2023-01-19 12:21 UTC, ph1p approved these changes

2023-01-19 12:22 UTC, merged